spring:
  datasource:
    url: jdbc:mysql://192.168.199.134:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1800000
      connection-timeout: 30000
      idle-timeout: 600000
      minimum-idle: 5
