# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
